### PR TITLE
FEATURES FEATURES FEATURES <3

### PR DESCRIPTION
**Pull request by yannickoo**

### CODE REVIEW

**Comment by zcei** [comment]
Huiuiui, insta-pull

**Comment by tonekk** [comment]
:ship:

**Comment by berlin1337** [comment]
Please release, I must dance

**Comment by frankyflow** [comment]
Please m8

**Comment by yolo71** [comment]
WALLAH https://github.com/tonekk/magda-closing

**Comment by yannickoo** [comment]
:sunglasses:

**Comment by redaktion** [comment]
Thanks for merge <3

**Pull request merged**
